config/routes.rb
Rails.application.routes.draw do

  devise_for :landlords
  devise_for :tenants

  root 'welcome#index'

  resources :tenants, only: :show
  resources :landlords, only: :show
  resources :rental_units do
    resources :bills, only: [:index, :update, :create, :destroy]
  end

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :rental_unit

  validates :month, presence: true
  validates :month, numericality: { only_integer: true,
                                    greater_than: 0, less_than: 13 }

  validates :amount, presence: true
  validates :amount, numericality: { only_integer: true,
                                     greater_than_or_equal_to: 0 }
end

app/models/electric_utility.rb
class ElectricUtility < ActiveRecord::Base
  has_many :rental_units

  validates :name, presence: true
end

app/models/gas_utility.rb
class GasUtility < ActiveRecord::Base
  has_many :rental_units

  validates :name, presence: true
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rental_units

  validates :email, presence: true
  validates :email, format: { with: /.+@.+\..+/i,
                              message: "Please enter a valid email address."}
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_many :rental_units

  validates :name, presence: true
end

app/models/rental_unit.rb
class RentalUnit < ActiveRecord::Base
  belongs_to :tenant
  belongs_to :landlord
  belongs_to :electric_utility
  belongs_to :gas_utility
  belongs_to :neighborhood
  has_many :bills, dependent: :destroy

  mount_uploaders :photos, ApartmentUploader

  geocoded_by :address
  after_validation :geocode

  validates :address, presence: true

  validates :number_of_bedrooms, presence: true
  validates :number_of_bedrooms,
    numericality: { only_integer: true,
                    greater_than: 0 }

  validates :type_of_dwelling, presence: true

  validates :monthly_rent, presence: true
  validates :monthly_rent,
    numericality: { only_integer: true,
                    greater_than: 0 }

  def street_address
    self.address.split(',')[0]
  end

  def city_state_zip
    address_array = self.address.split(',')
    if address_array.last.to_i !=0
      return address_array.last(3).join
    else
      return address_array.last(2).join
    end
  end

  def self.average_bills
    self.all.map { |unit| unit.bills.average(:amount).to_i }
  end

  def monthly_bills
    (1..12).map { |m| self.bills.where(month: m).average(:amount).to_i }
  end

  def utility_percentile
    self.class.average_bills.percentile_rank(self.monthly_bills.mean)
  end

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :rental_unit

  validates :email, presence: true
  validates :email, format: { with: /.+@.+\..+/i,
                              message: "Please enter a valid email address." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_tenant!
  before_action :set_rental_unit_and_bill, only: [:update, :destroy]

  def index
    @bills = Bills.where(rental_unit_id: params[:rental_unit_id])
  end

  def create
    @rental_unit = RentalUnit.find(params[:rental_unit_id])
    @bill = Bill.new(bill_params)
    @bill.rental_unit = @rental_unit

    if @bill.save
      flash[:notice] = 'Bill added!'
      redirect_to rental_unit_path(@rental_unit)
    else
      flash[:errors] = @bill.errors.full_messages.join(". ")
      redirect_to rental_unit_path(@rental_unit)
    end
  end

  def update
    @bill
    @rental_unit
    authorize_user(@rental_unit)
    @bill.update(month: bill_params[:month], amount: bill_params[:amount])
    if @bill.save
      redirect_to rental_unit_path(@rental_unit)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      redirect_to rental_unit_path(@rental_unit)
    end
  end

  def destroy
    @bill
    @rental_unit
    authorize_user(@rental_unit)
    @bill.destroy
    flash[:success] = 'Bill deleted.'
    redirect_to rental_unit_path(@rental_unit)
  end

  private

  def bill_params
    params.require(:bill).permit(:month, :amount, :rental_unit_id)
  end

  def authorize_user(rental_unit)
    unless current_tenant == rental_unit.tenant
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def set_rental_unit_and_bill
    @bill = Bills.find(params[:id])
    @rental_unit = @bill.rental_unit
  end
end

app/controllers/rental_units_controller.rb
class RentalUnitsController < ApplicationController
  def index
    @rental_units = RentalUnit.all
    gon.rental_units = @rental_units
    @average_bills = RentalUnit.average_bills
    gon.average_bills = @average_bills
  end

  def show
    @rental_unit = RentalUnit.find(params[:id])
    gon.rental_unit = @rental_unit
    @monthly_bills = @rental_unit.monthly_bills
    gon.monthly_bills = @monthly_bills
    @average_bills = RentalUnit.average_bills
    @utility_percentile = @rental_unit.utility_percentile
    @bill = Bill.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @rental_unit = RentalUnit.new
  end

  def create
    existing_unit = unique_address_checker(params[:rental_unit][:address])
    if existing_unit.nil?
      @rental_unit = RentalUnit.new(rental_unit_params)
      @rental_unit.tenant = current_tenant
    else
      flash[:notice] = 'Unit already exists! Here it is...'
      redirect_to rental_unit_path(existing_unit)
      return
    end

    if @rental_unit.utilities_included?
      estimated_bill = create_bill(@rental_unit)
      (1..12).each do |month|
        Bill.create(month: month, amount: estimated_bill, rental_unit: @rental_unit)
      end
    end

    if @rental_unit.save
      flash[:notice] = 'Rental unit added!'
      redirect_to rental_unit_path(@rental_unit)
    else
      flash[:error] = @rental_unit.errors.full_messages.join(". ") + "."
      render :new
    end
  end

  def destroy
    @rental_unit = RentalUnit.find(params[:id])
    authorize_tenant(@rental_unit)
    @rental_unit.destroy
    flash[:success] = 'Rental unit deleted.'
    redirect_to rental_units_path
  end

  private

  def create_bill(rental_unit)
    zillow_request = Zillow.new(rental_unit)
    rent_zestimate = zillow_request.get_rent_zestimate
    rental_unit.monthly_rent - rent_zestimate
  end

  def rental_unit_params
    params.require(:rental_unit).
      permit(
        :address, :number_of_bedrooms, :type_of_dwelling, :monthly_rent,
        :gas_utility_id, :electric_utility_id, :tenant_id, :landlord_id,
        :neighborhood_id, :utilities_included, photos: [])
  end

  def unique_address_checker(addr)
    rental_unit = RentalUnit.where(address: addr)

    if rental_unit.empty?
      nil
    else
      rental_unit.first
    end
  end

  def authorize_tenant(rental_unit)
    unless current_tenant == rental_unit.tenant
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/rental_units_controller/zillow.rb
class RentalUnitsController::Zillow
  include HTTParty
  base_uri 'http://www.zillow.com'
  debug_output

  def initialize(unit)
    @address = unit.street_address
    @citystatezip = unit.city_state_zip
    @options = { query: {:'zws-id' => ENV["ZWSID"], address: @address,
                         citystatezip: @citystatezip, rentzestimate: true }}
    response = self.class.get('/webservice/GetDeepSearchResults.htm', @options)
    @rent_zestimate = response["searchresults"]["response"]["results"]["result"]["rentzestimate"]["amount"]["__content__"].to_i
  end

  def get_rent_zestimate
    @rent_zestimate
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/rental_units_helper.rb
module RentalUnitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bills/_new_bill_form.html.erb
<%= simple_form_for [@rental_unit, @bill], remote: true do |f| %>
  <%= f.input :month, collection: 1..12,
    label_method: Proc.new { |m| I18n.t("date.month_names")[m] },
    selected: 1 %>
  <%= f.input :amount %>
  <%= f.button :submit, class: 'button radius', id: 'new-bill' %>
<% end %>

<script>
$(document).ready(
  $("#new_bill").on("ajax:success", function(event, data, status, xhr) {
    $("#newBill").foundation('reveal','close');
  })
)
</script>

app/views/bills/destroy.html.erb
<h1>Bills#destroy</h1>
<p>Find me in app/views/bills/destroy.html.erb</p>

app/views/bills/index.html.erb
<h1>Bills#index</h1>
<p>Find me in app/views/bills/index.html.erb</p>

app/views/bills/update.html.erb
<h1>Bills#update</h1>
<p>Find me in app/views/bills/update.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Rentr', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="right">
  <%- if current_tenant || current_landlord -%>
    <% if current_tenant %>
      <li><%= link_to "#{current_tenant.email}", tenant_path(current_tenant) %></li>
      <li><%= link_to 'Edit My Account', edit_tenant_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_tenant_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Profile', landlord_path(current_landlord) %></li>
      <li><%= link_to 'Edit My Account', edit_landlord_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_landlord_session_path, method: :delete %></li>
    <% end %>
  <%- else -%>
    <li class="has-dropdown">
      <a>Sign Up</a>
        <ul class="dropdown">
          <li><%= link_to 'as a Tenant', new_tenant_registration_path %></li>
          <li><%= link_to 'as a Landlord', new_landlord_registration_path %></li>
        </ul>
    </li>
    <li class="has-dropdown">
      <a>Sign In</a>
        <ul class="dropdown">
          <li><%= link_to 'as a Tenant', new_tenant_session_path %></li>
          <li><%= link_to 'as a Landlord', new_landlord_session_path %></li>
        </ul>
    </li>
  <%- end -%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rentr" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rentr" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag '//cdn.jsdelivr.net/jquery.slick/1.5.8/slick.css' %>
    <%= stylesheet_link_tag '//cdn.jsdelivr.net/jquery.slick/1.5.8/slick-theme.css' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= include_gon %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'https://www.google.com/jsapi' %>
    <%= javascript_include_tag '//cdn.jsdelivr.net/jquery.slick/1.5.8/slick.min.js' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <div id="bill-message"></div>
    </header>
    <main role="main">
      <div class="background-image"></div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/rental_units/_rental_unit_form.html.erb
<%= simple_form_for @rental_unit do |f| %>
  <%= f.input :address %>
  <%= f.input :number_of_bedrooms, collection: 0..7, selected: 0 %>
  <%= f.input :type_of_dwelling %>
  <%= f.input :monthly_rent %>
  <%= f.input :utilities_included %>
  <%= f.association :gas_utility, selected: "National Grid" %>
  <%= f.association :electric_utility, selected: "Eversource" %>
  <%= f.association :neighborhood %>
  <%= f.label :photos, "Add some photos!" %>
  <%= f.file_field :photos, multiple: true %>
  <%= f.button :submit, class: 'radius' %>
<% end %>

app/views/rental_units/index.html.erb
<div id="map"></div>

<div class="row">
  <div class="small-12 small-centered columns">
    <div class="panel apartment-metric">
      <span class="apartment-metric-text">As of <%= Date.today %>, the average monthly utility bill in Boston is</span>
      <span class="apartment-metric-number">$<%= @average_bills.mean.to_i %></span>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 medium-6 large-3 small-centered columns">
    <%= link_to 'Add a rental unit', new_rental_unit_path, class: 'button radius' %>
  </div>
</div>

<% google_maps_url = "https://maps.googleapis.com/maps/api/js?callback=initMap&key=#{ENV['GOOGLE_MAPS_BROWSER_API_KEY']}&libraries=visualization" %>
<script defer src=<%="#{google_maps_url}"%> %></script>

app/views/rental_units/new.html.erb
<div class="row">
  <%= render 'rental_unit_form' %>
</div>

app/views/rental_units/show.html.erb
<div id="newBill" class="reveal-modal" data-reveal aria-labelledby="New Bill" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">New Bill</h2>
  <%= render "bills/new_bill_form" %>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="confirmDelete" class="reveal-modal" data-reveal aria-labelledby="Delete Unit?" aria-hidden="true" role="dialog">
  <h2 id="modalTitle">Delete Unit?</h2>
  <ul class="button-group even-2 round">
    <li><%= link_to "Yes", rental_unit_path(@rental_unit), method: :delete,
            class: "button alert" %></li>
    <li><%= link_to "No", "", class: "button success", id: "noDelete" %></li>
  </ul>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div class="rental-unit-box">
  <div class="row">
    <div class="small-12 small-centered columns" id="rental-unit-title">
      <h2><%= @rental_unit.address %></h2>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns">
      <ul class="small-block-grid-1 medium-block-grid-3">
        <li><div class="apartment-info"><%= @rental_unit.type_of_dwelling %></div>
            <div class="apartment-info"><i class="fa fa-building left"></i><%= "#{@rental_unit.number_of_bedrooms} bedrooms" %></div>
            <div class="apartment-info"><i class="fa fa-money left"></i><%= "$#{@rental_unit.monthly_rent} per month" %></div>
            <div class="apartment-info"><i class="fa fa-fire left"></i><%= "#{@rental_unit.gas_utility.name}" %></div>
            <div class="apartment-info"><i class="fa fa-bolt left"></i> <%= "#{@rental_unit.electric_utility.name}" %></div>
            <div class="apartment-info"><i class="fa fa-location-arrow left"></i><%= "#{@rental_unit.neighborhood.name}" %></div>
        </li>
      <li><%= image_tag "https://maps.googleapis.com/maps/api/staticmap?size=300x300&markers=#{@rental_unit.latitude},#{@rental_unit.longitude}&key=#{ENV['GOOGLE_MAPS_BROWSER_API_KEY']}" %></li>
      <% if @rental_unit.photos.empty? %>
        <li><%= image_tag "http://maps.googleapis.com/maps/api/streetview?size=300x400&location=#{@rental_unit.latitude},#{@rental_unit.longitude}&key=#{ENV['GOOGLE_MAPS_BROWSER_API_KEY']}" %></li>
      <% else %>
        <li><div class="apartment-photos">
          <% @rental_unit.photos.each do |photo| %>
            <div><%= image_tag photo %></div>
          <% end %>
        </div></li>
      <% end %>
    </div>
  </div>

  <% unless @rental_unit.bills.empty? %>
    <div class="row">
      <div class="small-12 small-centered columns">
        <div id="bill-chart"></div>
      </div>
    </div>
  <% end %>

  <div class="row" data-equalizer data-equalizer-mq="medium-up">
    <div class="small-6 columns">
      <div class="panel apartment-metric" data-equalizer-watch>
        <span class="apartment-metric-text">This apartment's average monthly utility bill is </span>
        <span class="apartment-metric-number">$<%= @monthly_bills.mean.to_i %></span>
      </div>
    </div>
    <div class="small-6 columns">
      <div class="panel apartment-metric <%= "expensive" if @utility_percentile > 50 %>" data-equalizer-watch>
        <span class="apartment-metric-text">This is more expensive than </span>
        <span class="apartment-metric-number"> <%= @utility_percentile.to_i %>% </span>
        <span class="apartment-metric-text">of listed apartments.</span>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="small-12 columns show-for-medium-up">
      <ul class="button-group even-<%= current_tenant ? 3 : 2 %> round">
        <li><%= link_to "Back to list of rental units", rental_units_path, class:"button" %></li>
        <% if @rental_unit.tenant == current_tenant %>
          <% if !@rental_unit.utilities_included? %>
            <li><%= link_to "Add a bill for this unit", "",
              "data-reveal-id".to_sym => "newBill",
              class:"button", id: "new-bill" %></li>
          <% end %>
        <li><%= link_to "Delete this unit", "",
          "data-reveal-id".to_sym => "confirmDelete",
          class:"button alert", id: "confirm-delete" %></li>
        <% end %>
      </ul>
    </div>

    <div class="small-12 columns hide-for-medium-up">
      <ul class="button-group even-<%= current_tenant ? 3 : 2 %> round">
        <li><%= link_to "Back to list of rental units", rental_units_path, class:"button tiny" %></li>
        <% if @rental_unit.tenant == current_tenant %>
          <% if !@rental_unit.utilities_included? %>
            <li><%= link_to "Add a bill for this unit", "",
              "data-reveal-id".to_sym => "newBill",
              class:"button tiny", id: "new-bill" %></li>
          <% end %>
        <li><%= link_to "Delete this unit", "",
          "data-reveal-id".to_sym => "confirmDelete",
          class:"button alert tiny", id: "confirm-delete" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<script type="text/javascript">
  // Set a callback to run when the Google Visualization API is loaded.
  google.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.

  function drawChart() {

    var monthNames = ["January", "February", "March", "April", "May", "June",
      "July", "August", "September", "October", "November", "December"
      ];

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Month');
    data.addColumn('number', 'Average amount ($)');

    for (i=1;i<13;i++) {
      data.addRow([monthNames[i-1], gon.monthly_bills[i-1]]);
    }

    // Set chart options
    var options = {'title':'Utility Bills by Month',
                  legend: {position: 'none'},
                  backgroundColor: 'transparent',
                  vAxis: {format: 'currency'}
                 };

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.ColumnChart(document.getElementById('bill-chart'));
    chart.draw(data, options);

    }

    // Load the Visualization API and the piechart package.
    google.load('visualization', '1.0', {'packages':['corechart']});
</script>

app/views/rental_units/show.js.erb
<% if (flash[:errors] || flash[:notice]) %>
  $('#bill-message').html("<%= escape_javascript(render partial: 'layouts/messages') %>").show();
  setTimeout(function(){
    $("#bill-message").slideUp("slow", function() {
      $(this).empty();
    })
  }, 4500);
<% end %>

app/views/welcome/index.html.erb
<section class="hero">
  <div class="row intro">
    <div class="small-centered medium-uncentered medium-6 large-5 columns">
      <div class="tech-img"></div></div>
    <div class="small-centered medium-uncentered medium-10 large-12 columns">
      <h1>Find out what apartments really cost.</h1>
      </div>
    </div>
  </div>
</section>

<div class="row">
  <div class="small-12 small-centered columns show-for-medium-up">
    <div class="button-group even-<%= current_tenant ? 2 : 1 %> round">
      <%= link_to 'Find a rental unit', rental_units_path, class: 'button' %>
      <% if current_tenant %>
        <%= link_to 'Add your rental unit', new_rental_unit_path, class: 'button' %>
      <% end %>
    </div>
  </div>

  <div class="small-12 small-centered columns hide-for-medium-up">
    <div class="button-group even-<%= current_tenant ? 2 : 1 %> round">
      <%= link_to 'Find a rental unit', rental_units_path, class: 'button tiny' %>
      <% if current_tenant %>
        <%= link_to 'Add your rental unit', new_rental_unit_path, class: 'button tiny' %>
      <% end %>
    </div>
  </div>
</div>